[build-system]
requires = ["setuptools", "kaggle", "pandas", "sqlalchemy", "pyodbc"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "movies_load_pkg01"

# Alternative: use workspace configuration
# [tool.dagster]
# workspace_path = "workspace.py"
